# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5064441c33329478564a5bb9de8a879136f0a7becf9f227c115308d7798110b1213c1aca900422480d608a63d96456b93d9054964e1c2a0a5d6d912e93cd3b12

test:
  secret_key_base: 7ba106d12c650da24f43ec8b657429ba5de63ebc2fe9860e8e788a449973365942777c2ece9712eea1c43774e18a46ec3c68c4e05bfd72201491d621152d5b39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
